[package]
name = "eww"
version = "0.4.0"
authors = ["elkowar <5300871+elkowar@users.noreply.github.com>"]
description = "Widgets for everyone!"
license = "MIT"
repository = "https://github.com/elkowar/eww"
homepage = "https://github.com/elkowar/eww"
edition = "2021"



[features]
default = ["x11", "wayland"]
x11 = ["gdkx11", "x11rb"]
wayland = ["gtk-layer-shell"]

[dependencies]
gtk = { version = "0.15", features = [ "v3_22" ] }
gdk = "0.15"
glib = "0.15"

cairo-rs = "0.15"
cairo-sys-rs = "0.15.1"

gdk-pixbuf = "0.15"

gtk-layer-shell = { version = "0.4", optional = true}
gdkx11 = { version = "0.15", optional = true }
x11rb = { version = "0.11.1", features = ["randr"], optional = true }

regex = "1.7.3"
bincode = "1.3.3"
anyhow = "1.0.70"
derive_more = "0.99"
maplit = "1"
clap = {version = "4.1", features = ["derive"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
extend = "1.2"
grass = "0.12.3"
itertools = "0.10"
log = "0.4"
pretty_env_logger = "0.4"
libc = "0.2"
once_cell = "1.14"
nix = "0.26.2"
simple-signal = "1.1"
unescape = "0.1"

tokio = { version = "1.26.0", features = ["full"] }
futures-core = "0.3.27"
futures-util = "0.3.27"
tokio-util = "0.7.7"

sysinfo = "0.28.4"
chrono = "0.4.26"

wait-timeout = "0.2"

notify = "5.1.0"

codespan-reporting = "0.11"

simplexpr = { version = "0.1.0", path = "../simplexpr" }
eww_shared_util = { version = "0.1.0", path = "../eww_shared_util" }
yuck = { version = "0.1.0", path = "../yuck", default-features = false}
