# The URL the site will be built for
base_url = "https://elkowar.github.io/eww/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "book"

highlight_theme = "base16-ocean-dark"

[extra]
book_numbered_chapters = false
